export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
// Forum
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ALL_FORUMS = "GET_ALL_FORUMS";
export const GET_FORUM_BY_ID = "GET_FORUM_BY_ID";
export const GET_FORUM_BY_ID_ERROR = "GET_FORUM_BY_ID_ERROR";
export const GET_FORUM_IDS = "GET_FORUM_IDS";
export const GET_FORUM_IDS_ERROR = "GET_FORUM_IDS_ERROR";
export const CREATE_FORUM = "CREATE_FORUM";
// Forum Category
export const GET_ALL_FORUM_CATEGORIES = "GET_ALL_FORUM_CATEGORIES";
export const GET_FORUM_CATEGORY_BY_ID = "GET_FORUM_CATEGORY_BY_ID";
export const GET_FORUM_CATEGORY_BY_ID_ERROR = "GET_FORUM_CATEGORY_BY_ID_ERROR";
export const GET_FORUM_CATEGORY_IDS = "GET_FORUM_CATEGORY_IDS";
export const GET_FORUM_CATEGORY_IDS_ERROR = "GET_FORUM_CATEGORY_IDS_ERROR";
export const CREATE_FORUM_CATEGORY = "CREATE_FORUM_CATEGORY";
export const UPDATE_FORUM_CATEGORY = "UPDATE_FORUM_CATEGORY";
export const DELETE_FORUM_CATEGORY = "DELETE_FORUM_CATEGORY";
// Forum Topic
export const GET_ALL_FORUM_TOPICS = "GET_ALL_FORUM_TOPICS";
export const GET_FORUM_TOPIC_BY_ID = "GET_FORUM_TOPIC_BY_ID";
export const GET_FORUM_TOPIC_IDS = "GET_FORUM_TOPIC_IDS";
export const UPDATE_FORUM_TOPIC = "UPDATE_FORUM_TOPIC";
export const DELETE_FORUM_TOPIC = "DELETE_FORUM_TOPIC";
// Forum Post
export const CREATE_FORUM_POST = "CREATE_FORUM_POST";
export const GET_ALL_FORUM_POSTS = "GET_ALL_FORUM_POSTS";
export const GET_FORUM_POSTS_BY_TOPIC_ID = "GET_FORUM_POSTS_BY_TOPIC_ID";
export const GET_FORUM_POST_BY_ID = "GET_FORUM_POST_BY_ID";
export const DELETE_FORUM_POST = "DELETE_FORUM_POST";
export const CREATE_FORUM_TOPIC = "CREATE_FORUM_TOPIC";
// Forum Status
export const FORUM_ERROR = "FORUM_ERROR";
export const LOADING_FORUMS = "LOADING_FORUMS";
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const LOADING_TOPICS = "LOADING_TOPICS";
// Community
export const LOADING_COMMUNITIES = "LOADING_COMMUNITIES";
export const CREATE_COMMUNITY = "CREATE_COMMUNITY";
export const UPDATE_COMMUNITY = "UPDATE_COMMUNITY";
export const DELETE_COMMUNITY = "DELETE_COMMUNITY";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_ALL_COMMUNITIES = "GET_ALL_COMMUNITIES";
export const GET_COMMUNITY_BY_ID = "GET_COMMUNITY_BY_ID";
export const COMMUNITIES_ERROR = "COMMUNITIES_ERROR";
export const LOADING_COMMUNITY_GROUPS = "LOADING_COMMUNITY_GROUPS";
export const GET_COMMUNITY_GROUPS = "GET_COMMUNITY_GROUPS";
export const COMMUNITY_GROUPS_ERROR = "COMMUNITY_GROUPS_ERROR";
// Permissions / UserRank
export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const GET_RANK_PERMISSIONS = "GET_RANK_PERMISSIONS";
export const UPDATE_USER_RANK = "UPDATE_USER_RANK";
export const CREATE_USER_RANK = "CREATE_USER_RANK";
export const DELETE_USER_RANK = "DELETE_USER_RANK";
export const PERMISSIONS_ERROR = "PERMISSIONS_ERROR";
export const LOADING_PERMISSIONS = "LOADING_PERMISSIONS";
export const LOADING_RANK_PERMISSIONS = "LOADING_RANK_PERMISSIONS";
// Contributions
export const GET_ALL_CONTRIBUTIONS = "GET_ALL_CONTRIBUTIONS";
export const GET_COMMUNITY_CONTRIBUTIONS = "GET_COMMUNITY_CONTRIBUTIONS";
export const GET_GROUP_CONTRIBUTIONS = "GET_GROUP_CONTRIBUTIONS";
export const GET_CONTRIBUTION_BY_ID = "GET_CONTRIBUTION_BY_ID";
export const CREATE_CONTRIBUTION = "CREATE_CONTRIBUTION";
export const UPDATE_CONTRIBUTION = "UPDATE_CONTRIBUTION";
export const DELETE_CONTRIBUTION = "DELETE_CONTRIBUTION";
export const LOADING_CONTRIBUTIONS = "LOADING_CONTRIBUTIONS";
export const CONTRIBUTIONS_ERROR = "CONTRIBUTIONS_ERROR";
// Artists
export const GET_ALL_ARTISTS = "GET_ALL_ARTISTS";
export const GET_ARTIST_BY_ID = "GET_ARTIST_BY_ID";
export const LOADING_ARTISTS = "LOADING_ARTISTS";
export const UPDATE_ARTIST = "UPDATE_ARTIST";
export const GET_ARTIST_GROUPS = "GET_ARTIST_GROUPS";
export const ARTIST_GROUPS_ERROR = "ARTIST_GROUPS_ERROR";
export const LOADING_ARTIST_GROUPS = "LOADING_ARTIST_GROUPS";
export const ARTISTS_ERROR = "ARTISTS_ERROR";
// Users
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const LOADING_USERS = "LOADING_USERS";
export const USERS_ERROR = "USER_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_ERROR = "GET_USER_BY_ID_ERROR";
