const defaultUserRanks = [
  {
    field1: 100,
    field2: "User",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_advanced_search: true,
      site_top10: true,
      site_album_votes: true,
      site_edit_wiki: true,
      communities_add_artist: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 150,
    field2: "Member",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      zip_downloader: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 200,
    field2: "Power User",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      forums_polls_create: true,
      zip_downloader: true,
      communities_add_artist: true,
      MaxCollages: "1",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 250,
    field2: "Elite",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      forums_polls_create: true,
      site_delete_tag: true,
      zip_downloader: true,
      communities_edit: true,
      edit_unknowns: true,
      MaxCollages: "3",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 201,
    field2: "Artist",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_recommend_own: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 9,
  },
  {
    field1: 202,
    field2: "Donor",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      MaxCollages: "1",
    },
    field4: "",
    field5: "",
    field6: 10,
  },
  {
    field1: 205,
    field2: "Donor",
    field3: {
      site_vote: true,
      site_submit_requests: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      zip_downloader: true,
      communities_add_artist: true,
      MaxCollages: "1",
    },
    field4: "",
    field5: "",
    field6: 10,
  },
  {
    field1: 255,
    field2: "First Line Support",
    field3: {
      site_collages_personal: true,
      site_advanced_top10: true,
      MaxCollages: "1",
    },
    field4: "1",
    field5: "28",
    field6: 1,
  },
  {
    field1: 257,
    field2: "Recruiter",
    field3: {
      site_send_unlimited_invites: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 300,
    field2: "Interviewer",
    field3: {
      MaxCollages: "0",
    },
    field4: "",
    field5: "30",
    field6: 1,
  },
  {
    field1: 310,
    field2: "Community Celebrity",
    field3: {
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 320,
    field2: "Designer",
    field3: {
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      forums_polls_create: true,
      zip_downloader: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "5",
    },
    field4: "",
    field5: "33",
    field6: 1,
  },
  {
    field1: 330,
    field2: "Security Team",
    field3: {
      site_send_unlimited_invites: true,
      forums_polls_create: true,
      MaxCollages: "5",
    },
    field4: "1",
    field5: "",
    field6: 1,
  },
  {
    field1: 340,
    field2: "IRC Team",
    field3: {
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 350,
    field2: "Shadow Team",
    field3: {
      site_advanced_search: true,
      site_top10: true,
      site_advanced_top10: true,
      site_can_invite_always: true,
      site_send_unlimited_invites: true,
      site_disable_ip_history: true,
      users_edit_profiles: true,
      users_view_friends: true,
      users_disable_users: true,
      users_disable_posts: true,
      users_disable_any: true,
      users_view_invites: true,
      users_view_email: true,
      users_mod: true,
      admin_advanced_user_search: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 360,
    field2: "Alpha Team",
    field3: {
      admin_reports: true,
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 370,
    field2: "Bravo Team",
    field3: {
      MaxCollages: "0",
    },
    field4: "",
    field5: "",
    field6: 1,
  },
  {
    field1: 380,
    field2: "Charlie Team",
    field3: {
      site_vote: true,
      site_submit_requests: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_moderate_requests: true,
      site_delete_artist: true,
      site_delete_tag: true,
      zip_downloader: true,
      site_tag_aliases_read: true,
      communities_edit: true,
      communities_delete: true,
      communities_add_artist: true,
      edit_unknowns: true,
      communities_fix_ghosts: true,
      MaxCollages: "2",
    },
    field4: "",
    field5: "31",
    field6: 1,
  },
  {
    field1: 395,
    field2: "Delta Team",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_can_invite_always: true,
      MaxCollages: "1",
    },
    field4: "",
    field5: "35",
    field6: 1,
  },
  {
    field1: 400,
    field2: "Community Lead",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      forums_polls_create: true,
      site_delete_tag: true,
      zip_downloader: true,
      communities_edit: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "6",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 450,
    field2: "Power CL",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      forums_polls_create: true,
      site_delete_tag: true,
      zip_downloader: true,
      communities_edit: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "5",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 500,
    field2: "Elite CL",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_send_unlimited_invites: true,
      forums_polls_create: true,
      site_delete_tag: true,
      zip_downloader: true,
      communities_edit: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "6",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 601,
    field2: "VIP",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_send_unlimited_invites: true,
      forums_polls_create: true,
      site_delete_tag: true,
      zip_downloader: true,
      communities_edit: true,
      communities_add_artist: true,
      edit_unknowns: true,
      MaxCollages: "6",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 605,
    field2: "Legend",
    field3: {
      MaxCollages: "1",
    },
    field4: "",
    field5: "",
    field6: 0,
  },
  {
    field1: 800,
    field2: "Forum Moderator",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_send_unlimited_invites: true,
      forums_polls_create: true,
      site_moderate_forums: true,
      site_admin_forums: true,
      site_delete_tag: true,
      site_disable_ip_history: true,
      zip_downloader: true,
      site_proxy_images: true,
      site_search_many: true,
      site_forums_double_post: true,
      project_team: true,
      site_tag_aliases_read: true,
      users_edit_titles: true,
      users_edit_avatars: true,
      users_warn: true,
      users_disable_posts: true,
      users_override_paranoia: true,
      communities_edit: true,
      communities_delete: true,
      communities_add_artist: true,
      edit_unknowns: true,
      admin_reports: true,
      MaxCollages: "6",
    },
    field4: "1",
    field5: "",
    field6: 0,
  },
  {
    field1: 850,
    field2: "Community Moderator",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_send_unlimited_invites: true,
      site_delete_artist: true,
      forums_polls_create: true,
      site_moderate_forums: true,
      site_admin_forums: true,
      site_view_community_snatchlist: true,
      site_delete_tag: true,
      site_disable_ip_history: true,
      zip_downloader: true,
      site_proxy_images: true,
      site_search_many: true,
      site_forums_double_post: true,
      project_team: true,
      site_tag_aliases_read: true,
      users_edit_avatars: true,
      users_edit_reset_keys: true,
      users_view_friends: true,
      users_warn: true,
      users_disable_users: true,
      users_disable_posts: true,
      users_view_seedleech: true,
      users_view_uploaded: true,
      users_view_keys: true,
      users_view_ips: true,
      users_view_email: true,
      users_invite_notes: true,
      users_override_paranoia: true,
      users_mod: true,
      communities_edit: true,
      communities_delete: true,
      communities_delete_fast: true,
      communities_search_fast: true,
      communities_add_artist: true,
      edit_unknowns: true,
      communities_fix_ghosts: true,
      admin_reports: true,
      admin_advanced_user_search: true,
      admin_clear_cache: true,
      admin_whitelist: true,
      MaxCollages: "6",
    },
    field4: "1",
    field5: "",
    field6: 0,
  },
  {
    field1: 900,
    field2: "Moderator",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_delete: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_send_unlimited_invites: true,
      site_moderate_requests: true,
      site_delete_artist: true,
      forums_polls_create: true,
      site_moderate_forums: true,
      site_admin_forums: true,
      site_view_community_snatchlist: true,
      site_delete_tag: true,
      site_disable_ip_history: true,
      zip_downloader: true,
      site_proxy_images: true,
      site_search_many: true,
      site_forums_double_post: true,
      project_team: true,
      site_tag_aliases_read: true,
      users_edit_titles: true,
      users_edit_avatars: true,
      users_edit_invites: true,
      users_edit_reset_keys: true,
      users_view_friends: true,
      users_warn: true,
      users_disable_users: true,
      users_disable_posts: true,
      users_disable_any: true,
      users_view_invites: true,
      users_view_seedleech: true,
      users_view_uploaded: true,
      users_view_keys: true,
      users_view_ips: true,
      users_view_email: true,
      users_invite_notes: true,
      users_override_paranoia: true,
      users_mod: true,
      communities_edit: true,
      communities_delete: true,
      communities_delete_fast: true,
      communities_freeleech: true,
      communities_search_fast: true,
      communities_add_artist: true,
      edit_unknowns: true,
      communities_fix_ghosts: true,
      admin_manage_fls: true,
      admin_reports: true,
      admin_advanced_user_search: true,
      admin_clear_cache: true,
      admin_whitelist: true,
      MaxCollages: "6",
    },
    field4: "1",
    field5: "",
    field6: 0,
  },
  {
    field1: 950,
    field2: "Developer",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_can_invite_always: true,
      site_send_unlimited_invites: true,
      forums_polls_create: true,
      site_view_flow: true,
      site_view_full_log: true,
      site_view_community_snatchlist: true,
      site_recommend_own: true,
      site_manage_recommendations: true,
      site_delete_tag: true,
      zip_downloader: true,
      site_forums_double_post: true,
      MaxCollages: "1",
    },
    field4: "1",
    field5: "35",
    field6: 0,
  },
  {
    field1: 980,
    field2: "Administrator",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_delete: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_can_invite_always: true,
      site_send_unlimited_invites: true,
      site_moderate_requests: true,
      site_delete_artist: true,
      forums_polls_create: true,
      forums_polls_moderate: true,
      site_moderate_forums: true,
      site_admin_forums: true,
      site_view_flow: true,
      site_view_full_log: true,
      site_view_community_snatchlist: true,
      site_recommend_own: true,
      site_manage_recommendations: true,
      site_delete_tag: true,
      site_disable_ip_history: true,
      zip_downloader: true,
      site_proxy_images: true,
      site_search_many: true,
      site_collages_recover: true,
      site_forums_double_post: true,
      site_tag_aliases_read: true,
      users_edit_ratio: true,
      users_edit_titles: true,
      users_edit_avatars: true,
      users_edit_invites: true,
      users_edit_watch_hours: true,
      users_edit_reset_keys: true,
      users_edit_profiles: true,
      users_view_friends: true,
      users_reset_own_keys: true,
      users_edit_password: true,
      users_promote_below: true,
      users_warn: true,
      users_disable_users: true,
      users_disable_posts: true,
      users_disable_any: true,
      users_delete_users: true,
      users_view_invites: true,
      users_view_seedleech: true,
      users_view_uploaded: true,
      users_view_keys: true,
      users_view_ips: true,
      users_view_email: true,
      users_invite_notes: true,
      users_override_paranoia: true,
      users_mod: true,
      communities_edit: true,
      communities_delete: true,
      communities_delete_fast: true,
      communities_freeleech: true,
      communities_search_fast: true,
      communities_hide_dnu: true,
      communities_add_artist: true,
      edit_unknowns: true,
      admin_manage_news: true,
      admin_manage_blog: true,
      admin_manage_polls: true,
      admin_manage_forums: true,
      admin_manage_fls: true,
      admin_reports: true,
      admin_advanced_user_search: true,
      admin_create_users: true,
      admin_donor_log: true,
      admin_manage_ipbans: true,
      admin_dnu: true,
      admin_clear_cache: true,
      admin_whitelist: true,
      admin_manage_permissions: true,
      admin_schedule: true,
      admin_login_watch: true,
      admin_manage_wiki: true,
      admin_update_geoip: true,
      site_collages_recover: true,
      communities_add_artist: true,
      edit_unknowns: true,
      forums_polls_create: true,
      forums_polls_moderate: true,
      project_team: true,
      communities_edit_vanityhouse: true,
      artist_edit_vanityhouse: true,
      site_tag_aliases_read: true,
    },
    field4: "1",
    field5: "",
    field6: 0,
  },
  {
    field1: 1000,
    field2: "SysOp",
    field3: {
      site_leech: true,
      site_upload: true,
      site_vote: true,
      site_submit_requests: true,
      site_advanced_search: true,
      site_top10: true,
      site_advanced_top10: true,
      site_album_votes: true,
      site_communities_notify: true,
      site_collages_create: true,
      site_collages_manage: true,
      site_collages_delete: true,
      site_collages_subscribe: true,
      site_collages_personal: true,
      site_collages_renamepersonal: true,
      site_make_bookmarks: true,
      site_edit_wiki: true,
      site_can_invite_always: true,
      site_send_unlimited_invites: true,
      site_moderate_requests: true,
      site_delete_artist: true,
      site_moderate_forums: true,
      site_admin_forums: true,
      site_forums_double_post: true,
      site_view_flow: true,
      site_view_full_log: true,
      site_view_community_snatchlist: true,
      site_recommend_own: true,
      site_manage_recommendations: true,
      site_delete_tag: true,
      site_disable_ip_history: true,
      zip_downloader: true,
      site_debug: true,
      site_proxy_images: true,
      site_search_many: true,
      users_edit_usernames: true,
      users_edit_ratio: true,
      users_edit_own_ratio: true,
      users_edit_titles: true,
      users_edit_avatars: true,
      users_edit_invites: true,
      users_edit_watch_hours: true,
      users_edit_reset_keys: true,
      users_edit_profiles: true,
      users_view_friends: true,
      users_reset_own_keys: true,
      users_edit_password: true,
      users_promote_below: true,
      users_promote_to: true,
      users_give_donor: true,
      users_warn: true,
      users_disable_users: true,
      users_disable_posts: true,
      users_disable_any: true,
      users_delete_users: true,
      users_view_invites: true,
      users_view_seedleech: true,
      users_view_uploaded: true,
      users_view_keys: true,
      users_view_ips: true,
      users_view_email: true,
      users_invite_notes: true,
      users_override_paranoia: true,
      users_logout: true,
      users_make_invisible: true,
      users_mod: true,
      communities_edit: true,
      communities_delete: true,
      communities_delete_fast: true,
      communities_freeleech: true,
      communities_search_fast: true,
      communities_hide_dnu: true,
      communities_fix_ghosts: true,
      admin_manage_news: true,
      admin_manage_blog: true,
      admin_manage_polls: true,
      admin_manage_forums: true,
      admin_manage_fls: true,
      admin_reports: true,
      admin_advanced_user_search: true,
      admin_create_users: true,
      admin_donor_log: true,
      admin_manage_ipbans: true,
      admin_dnu: true,
      admin_clear_cache: true,
      admin_whitelist: true,
      admin_manage_permissions: true,
      admin_schedule: true,
      admin_login_watch: true,
      admin_manage_wiki: true,
      admin_update_geoip: true,
      site_collages_recover: true,
      communities_add_artist: true,
      edit_unknowns: true,
      forums_polls_create: true,
      forums_polls_moderate: true,
      project_team: true,
      communities_edit_vanityhouse: true,
      artist_edit_vanityhouse: true,
      site_tag_aliases_read: true,
    },
    field4: "1",
    field5: "",
    field6: 0,
  },
];

module.exports = { defaultUserRanks };
