const mongoose = require('mongoose');

const user123 = mongoose.Types.ObjectId('6498dc9f976b9f32be1268a1');
const user456 = mongoose.Types.ObjectId('6498f7b5452479fe28d2b327');
const user789 = mongoose.Types.ObjectId('649a2a8d7c90e1024a5a5f12');
const staff = mongoose.Types.ObjectId('649bb564e5e03231991e5da1');


// Sample seed data for ForumCategory
const forumCategoriesData = [
  { _id: mongoose.Types.ObjectId(), Name: 'Site', Sort: 1 },
  { _id: mongoose.Types.ObjectId(), Name: 'Suggestions', Sort: 3 },
  { _id: mongoose.Types.ObjectId(), Name: 'Community', Sort: 5 },
  { _id: mongoose.Types.ObjectId(), Name: 'Music', Sort: 8 },
  { _id: mongoose.Types.ObjectId(), Name: 'Help', Sort: 10 },
  { _id: mongoose.Types.ObjectId(), Name: 'Trash', Sort: 20 },
];

// Generate ForumCategory documents
const forumCategories = forumCategoriesData.map(categoryData => ({
  ...categoryData,
}));

// Sample seed data for Forum
  const forums = [
  {_id: mongoose.Types.ObjectId(),
Sort: 300,
    Name: 'Announcements..2?',
    Description: 'There are a terrible lot of lies going about the world and the worst of it is that half of them are true.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[0]._id,
  },
  {_id: mongoose.Types.ObjectId(),
   Sort: 1200,
    Name: 'Stellar',
    Description: 'Stellargraph',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id,
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 40,
    Name: 'Help!',
    Description: 'He that gives good advice builds with one hand, he that gives good counsel and example builds with both',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id,
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 5,
    Name: 'Trash',
    Description: 'Every thread ends up here eventually',
    MinClassRead: 100,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[3]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 200,
    Name: 'Staff',
    Description: 'No place like home',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[4]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 400,
    Name: 'Bugs',
    Description: 'Some days you are the bug, some days you are the windshield',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[0]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 100,
    Name: 'The Laboratory',
    Description: 'I was working in the lab late one night when my eyes beheld an eerie sight',
    MinClassRead: 1000,
    MinClassWrite: 1000,
    MinClassCreate: 1000,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 30,
    Name: 'Music',
    Description: '[this witty remark works only when accompanied by the sweet harmonies of acoustic guitars]',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1400,
    Name: 'Artists',
    Description: 'For the artists',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1500,
    Name: 'Donors',
    Description: 'I have a heart',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[3]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1600,
    Name: 'Elites',
    Description: 'I\'m 1337',
    MinClassRead: 250,
    MinClassWrite: 250,
    MinClassCreate: 250,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 600,
    Name: 'Announcements',
    Description: 'Public service announcements',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 800,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 2990,
    Name: 'Suggestions/Ideas',
    Description: 'My great concern is not whether you have failed, but whether you are content with your failure',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 43,
    Name: 'Contests & Designs',
    Description: 'Destiny is not a matter of chance, it is a matter of choice. It is not a thing to be waited for, it is a thing to be achieved.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 31,
    Name: 'Vanity House',
    Description: 'Without freedom no art; art lives only on the restraints it imposes on itself, and dies of all others.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[4]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 33,
    Name: 'Projects',
    Description: 'Daring ideas are like chessmen moved forward, they may be beaten, but they may start a winning game',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[4]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1700,
    Name: 'Concerts and Events',
    Description: 'I\'m off to a gig',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[3]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1800,
    Name: 'Comics',
    Description: 'I read comics',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1100,
    Name: 'The Library',
    Description: 'The first sign of maturity is the discovery that the volume knob also turns to the left',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 800,
    Name: 'First Line Support',
    Description: 'Special Support Operations Command (SSOC)',
    MinClassRead: 900,
    MinClassWrite: 900,
    MinClassCreate: 900,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[1]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1300,
    Name: 'Power User',
    Description: 'PU Forum <3',
    MinClassRead: 200,
    MinClassWrite: 200,
    MinClassCreate: 200,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1670,
    Name: 'Invitations',
    Description: 'Stairway to Heaven',
    MinClassRead: 250,
    MinClassWrite: 250,
    MinClassCreate: 250,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id, 
  },
  {_id: mongoose.Types.ObjectId(),
    Sort: 1610,
    Name: 'Community Leaders',
    Description: 'The Holy Grail',
    MinClassRead: 400,
    MinClassWrite: 400,
    MinClassCreate: 400,
    LastPostTopic: null,
    LastPost: null,
    ForumCategory: forumCategories[2]._id, 
  },
];

const forumTopics = [
  {
    Title: 'Finances Update / Introducing the Whatminimal Shirt',
    Author: user123,
    LastPost: null,
    LastPostAuthor: user123,
    IsLocked: true,
    NumPosts: 1,
    Forum: forums[0]._id
  },
  {
    Title: "We'll Add Bounty to Your Requests!",
    Author: staff,
    LastPost: null,
    LastPostAuthor: staff,
    NumPosts: 22,
    Forum: forums[0]._id
  },
  {
    Title: 'The Stellar CD Design Thread',
    Author: user456,
    LastPost: null,
    NumPosts: 99,
    Forum: forums[0]._id
  },
  {
    Title: 'Approved Ripping Tools: Morituri',
    Author: user789,
    LastPost: null,
    NumPosts: 1232,
    Forum: forums[0]._id
  },
  {
    Title: 'Automatically update your existing library to better quality',
    Author: user123,
    LastPost: null,
    NumPosts: 21,
    Forum: forums[0]._id
  },
  {
    Title: 'Add a country of origin field to music communities',
    Author: user456,
    LastPost: null,
    NumPosts: 13,
    Forum: forums[0]._id
  },
  {
    Title: "Notifications I didn't sign up for",
    Author: user789,
    LastPost: null,
    NumPosts: 3,
    Forum: forums[0]._id
  },
  {
    Title: 'Lets Talk Football!',
    Author: user123,
    LastPost: null,
    NumPosts: 233,
    Forum: forums[0]._id
  },
  {
    Title: 'TMI',
    Author: user456,
    LastPost: null,
    NumPosts: 213,
    Forum: forums[0]._id
  },
  {
    Title: 'Where is meaning if it depends on both subject and object?',
    Author: user789,
    LastPost: null,
    NumPosts: 5133,
    Forum: forums[0]._id
  },
  {
    Title: '[Region] The London Thread',
    Author: user123,
    LastPost: null,
    NumPosts: 22,
    Forum: forums[0]._id
  },
  {
    Title: 'Your favorite comic publisher???',
    Author: user456,
    LastPost: null,
    NumPosts: 22,
    Forum: forums[0]._id
  },
  {
    Title: 'Portable Media Players',
    Author: user789,
    LastPost: null,
    NumPosts: 2214,
    Forum: forums[0]._id
  },
  {
    Title: 'New Daft Punk Album This Spring',
    Author: user123,
    LastPost: null,
    NumPosts: 414,
    Forum: forums[0]._id
  },
  {
    Title: 'The Stellar CD, 2023, April: Music Submission Round!',
    Author: user456,
    LastPost: null,
    NumPosts: 23,
    Forum: forums[0]._id
  }
];

module.exports = {forumTopics, forumCategories, forums}