const mongoose = require('mongoose');

const user123 = mongoose.Types.ObjectId('6498dc9f976b9f32be1268a1');
const user456 = mongoose.Types.ObjectId('6498f7b5452479fe28d2b327');
const user789 = mongoose.Types.ObjectId('649a2a8d7c90e1024a5a5f12');
const staff = mongoose.Types.ObjectId('649bb564e5e03231991e5da1');


// Sample seed data for ForumCategory
const forumCategories = [
  { Name: 'Site', Sort: 1 },
  { Name: 'Suggestions', Sort: 3 },
  { Name: 'Community', Sort: 5 },
  { Name: 'Music', Sort: 8 },
  { Name: 'Help', Sort: 10 },
  { Name: 'Trash', Sort: 20 },
];

// Sample seed data for Forum
const forums = [
  {
    Sort: 300,
    Name: 'Announcements..2?',
    Description: 'There are a terrible lot of lies going about the world and the worst of it is that half of them are true.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1460c')
  },
  {
    Sort: 1200,
    Name: 'Stellar',
    Description: 'Stellargraph',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1460d')
  },
  {
    Sort: 40,
    Name: 'Help!',
    Description: 'He that gives good advice builds with one hand, he that gives good counsel and example builds with both',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1460e')
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1460f'),
    Sort: 5,
    Name: 'Trash',
    Description: 'Every thread ends up here eventually',
    MinClassRead: 100,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14610'),
    Sort: 200,
    Name: 'Staff',
    Description: 'No place like home',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14611'),
    Sort: 400,
    Name: 'Bugs',
    Description: 'Some days you are the bug, some days you are the windshield',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14612'),
    Sort: 100,
    Name: 'The Laboratory',
    Description: 'I was working in the lab late one night when my eyes beheld an eerie sight',
    MinClassRead: 1000,
    MinClassWrite: 1000,
    MinClassCreate: 1000,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14613'),
    Sort: 30,
    Name: 'Music',
    Description: '[this witty remark works only when accompanied by the sweet harmonies of acoustic guitars]',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14614'),
    Sort: 1400,
    Name: 'Artists',
    Description: 'For the artists',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14615'),
    Sort: 1500,
    Name: 'Donors',
    Description: 'I have a heart',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14616'),
    Sort: 1600,
    Name: 'Elites',
    Description: 'I\'m 1337',
    MinClassRead: 250,
    MinClassWrite: 250,
    MinClassCreate: 250,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14617'),
    Sort: 600,
    Name: 'Announcements',
    Description: 'Public service announcements',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14618'),
    Sort: 2990,
    Name: 'Suggestions/Ideas',
    Description: 'My great concern is not whether you have failed, but whether you are content with your failure',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14619'),
    Sort: 101,
    Name: 'Resolved Bugs',
    Description: 'The bug I reported has been fixed',
    MinClassRead: 100,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461a'),
    Sort: 3500,
    Name: 'Denied',
    Description: 'The suggestion I made has been denied',
    MinClassRead: 100,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461b'),
    Sort: 42,
    Name: 'Tutorials',
    Description: 'I would like to share my knowledge',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461c'),
    Sort: 43,
    Name: 'Contests & Designs',
    Description: 'Destiny is not a matter of chance, it is a matter of choice. It is not a thing to be waited for, it is a thing to be achieved.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461d'),
    Sort: 31,
    Name: 'Vanity House',
    Description: 'Without freedom no art; art lives only on the restraints it imposes on itself, and dies of all others.',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461e'),
    Sort: 32,
    Name: 'The Studio',
    Description: 'I\'m a DJ',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1461f'),
    Sort: 33,
    Name: 'Projects',
    Description: 'Daring ideas are like chessmen moved forward, they may be beaten, but they may start a winning game',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14620'),
    Sort: 1700,
    Name: 'Concerts and Events',
    Description: 'I\'m off to a gig',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14621'),
    Sort: 1800,
    Name: 'Comics',
    Description: 'I read comics',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14622'),
    Sort: 1900,
    Name: 'Technology',
    Description: 'I like technology',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14623'),
    Sort: 2000,
    Name: 'Projects',
    Description: 'I\'m working on a project',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14624'),
    Sort: 2100,
    Name: 'Games',
    Description: 'I\'m a gamer',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14625'),
    Sort: 34,
    Name: 'Vinyl',
    Description: 'Vinyl\'s are here to stay',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14626'),
    Sort: 1100,
    Name: 'The Library',
    Description: 'The first sign of maturity is the discovery that the volume knob also turns to the left',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14627'),
    Sort: 800,
    Name: 'First Line Support',
    Description: 'Special Support Operations Command (SSOC)',
    MinClassRead: 900,
    MinClassWrite: 900,
    MinClassCreate: 900,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14628'),
    Sort: 1300,
    Name: 'Power User',
    Description: 'PU Forum <3',
    MinClassRead: 200,
    MinClassWrite: 200,
    MinClassCreate: 200,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14629'),
    Sort: 900,
    Name: 'Interviewers',
    Description: 'The Candidates',
    MinClassRead: 900,
    MinClassWrite: 900,
    MinClassCreate: 900,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462a'),
    Sort: 1000,
    Name: 'Charlie Team',
    Description: 'Quality Assurance',
    MinClassRead: 850,
    MinClassWrite: 850,
    MinClassCreate: 850,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462b'),
    Sort: 20,
    Name: 'Audiophile',
    Description: 'For the audiophile',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462c'),
    Sort: 750,
    Name: 'Designers',
    Description: 'Designers',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462d'),
    Sort: 41,
    Name: 'Editing',
    Description: 'Quality Control',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 100,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462e'),
    Sort: 250,
    Name: 'Developers',
    Description: 'Developers forum',
    MinClassRead: 800,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a1462f'),
    Sort: 3000,
    Name: 'Approved',
    Description: 'Self-explanatory...',
    MinClassRead: 100,
    MinClassWrite: 100,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14630'),
    Sort: 3400,
    Name: 'Implemented',
    Description: 'The suggestion I made has been implemented',
    MinClassRead: 100,
    MinClassWrite: 800,
    MinClassCreate: 800,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14631'),
    Sort: 1650,
    Name: 'VIP',
    Description: 'Very Important Phorum',
    MinClassRead: 601,
    MinClassWrite: 601,
    MinClassCreate: 601,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14632'),
    Sort: 1670,
    Name: 'Invitations',
    Description: 'Stairway to Heaven',
    MinClassRead: 250,
    MinClassWrite: 250,
    MinClassCreate: 250,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
  {
    CategoryID:  mongoose.Types.ObjectId('649e4364dbc3721458a14633'),
    Sort: 1610,
    Name: 'Community Leaders',
    Description: 'The Holy Grail',
    MinClassRead: 400,
    MinClassWrite: 400,
    MinClassCreate: 400,
    LastPostTopicID: null,
    LastPostAuthorID: null,
    LastPostID: null,
  },
];

const forumTopics = [
  {
    Title: 'Finances Update / Introducing the Whatminimal Shirt',
    AuthorID: user123,
    LastPostID: null,
    LastPostAuthorID: user123,
    IsLocked: true,
    NumPosts: 1
  },
  {
    Title: "We'll Add Bounty to Your Requests!",
    AuthorID: staff,
    LastPostID: null,
    LastPostAuthorID: staff,
    NumPosts: 22
  },
  {
    Title: 'The What.CD Design Thread',
    AuthorID: user456,
    LastPostID: null,
    LastPostAuthorID: user456,
    NumPosts: 99
  },
  {
    Title: 'Approved Ripping Tools: Morituri',
    AuthorID: user789,
    LastPostID: null,
    LastPostAuthorID: user789,
    NumPosts: 1232
  },
  {
    Title: 'Automatically update your existing library to better quality',
    AuthorID: user123,
    LastPostID: null,
    LastPostAuthorID: user123,
    NumPosts: 21
  },
  {
    Title: 'Add a country of origin field to music torrents',
    AuthorID: user456,
    LastPostID: null,
    LastPostAuthorID: user456,
    NumPosts: 13
  },
  {
    Title: "Notifications I didn't sign up for",
    AuthorID: user789,
    LastPostID: null,
    LastPostAuthorID: user789,
    NumPosts: 3
  },
  {
    Title: 'Lets Talk Football!',
    AuthorID: user123,
    LastPostID: null,
    LastPostAuthorID: user123,
    NumPosts: 233
  },
  {
    Title: 'TMI',
    AuthorID: user456,
    LastPostID: null,
    LastPostAuthorID: user456,
    NumPosts: 213
  },
  {
    Title: 'Where is meaning if it depends on both subject and object?',
    AuthorID: user789,
    LastPostID: null,
    LastPostAuthorID: user789,
    NumPosts: 5133
  },
  {
    Title: '[Region] The London Thread',
    AuthorID: user123,
    LastPostID: null,
    LastPostAuthorID: user123,
    NumPosts: 22
  },
  {
    Title: 'Your favorite comic publisher???',
    AuthorID: user456,
    LastPostID: null,
    LastPostAuthorID: user456,
    NumPosts: 22
  },
  {
    Title: 'Portable Media Players',
    AuthorID: user789,
    LastPostID: null,
    LastPostAuthorID: user789,
    NumPosts: 2214
  },
  {
    Title: 'New Daft Punk Album This Spring',
    AuthorID: user123,
    LastPostID: null,
    LastPostAuthorID: user123,
    NumPosts: 414
  },
  {
    Title: 'The Stellar CD, 2023, April: Music Submission Round!',
    AuthorID: user456,
    LastPostID: null,
    LastPostAuthorID: user456,
    NumPosts: 23
  }
];

module.exports = {forumTopics, forumCategories, forums}