const mongoose = require("mongoose");

// all TimApple test user for now
const user123 = mongoose.Types.ObjectId("649bb564e5e03231991e5da1");
const user456 = mongoose.Types.ObjectId("649bb564e5e03231991e5da1");
const user789 = mongoose.Types.ObjectId("649bb564e5e03231991e5da1");
const staff = mongoose.Types.ObjectId("649bb564e5e03231991e5da1");

// Sample seed data for ForumCategory
const forumCategoriesData = [
  { _id: mongoose.Types.ObjectId(), name: "Site", sort: 1 },
  { _id: mongoose.Types.ObjectId(), name: "Suggestions", sort: 3 },
  { _id: mongoose.Types.ObjectId(), name: "Community", sort: 5 },
  { _id: mongoose.Types.ObjectId(), name: "Music", sort: 8 },
  { _id: mongoose.Types.ObjectId(), name: "Help", sort: 10 },
  { _id: mongoose.Types.ObjectId(), name: "Trash", sort: 20 },
];

// Generate ForumCategory documents
const forumCategories = forumCategoriesData.map((categoryData) => ({
  ...categoryData,
}));

// Sample seed data for Forum
const forums = [
  {
    _id: mongoose.Types.ObjectId(),
    sort: 300,
    name: "Announcements",
    description:
      "There are a terrible lot of lies going about the world and the worst of it is that half of them are true.",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[0]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1200,
    name: "Stellar",
    description: "Stellargraph",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[0]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 40,
    name: "Help!",
    description:
      "He that gives good advice builds with one hand, he that gives good counsel and example builds with both",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[4]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 5,
    name: "Trash",
    description: "Every thread ends up here eventually",
    minClassRead: 100,
    minClassWrite: 800,
    minClassCreate: 800,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[5]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 200,
    name: "Staff",
    description: "No place like home",
    minClassRead: 800,
    minClassWrite: 800,
    minClassCreate: 800,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[4]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 400,
    name: "Bugs",
    description: "Some days you are the bug, some days you are the windshield",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[0]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 100,
    name: "The Laboratory",
    description:
      "I was working in the lab late one night when my eyes beheld an eerie sight",
    minClassRead: 1000,
    minClassWrite: 1000,
    minClassCreate: 1000,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[1]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 30,
    name: "Music",
    description:
      "[this witty remark works only when accompanied by the sweet harmonies of acoustic guitars]",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1400,
    name: "Artists",
    description: "For the artists",
    minClassRead: 800,
    minClassWrite: 800,
    minClassCreate: 800,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1500,
    name: "Donors",
    description: "I have a heart",
    minClassRead: 800,
    minClassWrite: 800,
    minClassCreate: 800,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[3]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1600,
    name: "Elites",
    description: "I'm 1337",
    minClassRead: 250,
    minClassWrite: 250,
    minClassCreate: 250,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[3]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 2990,
    name: "Suggestions/Ideas",
    description:
      "My great concern is not whether you have failed, but whether you are content with your failure",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[1]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 43,
    name: "Contests & Designs",
    description:
      "Destiny is not a matter of chance, it is a matter of choice. It is not a thing to be waited for, it is a thing to be achieved.",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[1]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 31,
    name: "Vanity House",
    description:
      "Without freedom no art; art lives only on the restraints it imposes on itself, and dies of all others.",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[3]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 33,
    name: "Projects",
    description:
      "Daring ideas are like chessmen moved forward, they may be beaten, but they may start a winning game",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[0]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1700,
    name: "Concerts and Events",
    description: "I'm off to a gig",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[3]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1800,
    name: "Comics",
    description: "I read comics",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1100,
    name: "The Library",
    description:
      "The first sign of maturity is the discovery that the volume knob also turns to the left",
    minClassRead: 100,
    minClassWrite: 100,
    minClassCreate: 100,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 800,
    name: "First Line Support",
    description: "Special Support Operations Command (SSOC)",
    minClassRead: 900,
    minClassWrite: 900,
    minClassCreate: 900,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[1]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1300,
    name: "Power User",
    description: "PU Forum <3",
    minClassRead: 200,
    minClassWrite: 200,
    minClassCreate: 200,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1670,
    name: "Invitations",
    description: "Stairway to Heaven",
    minClassRead: 250,
    minClassWrite: 250,
    minClassCreate: 250,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
  {
    _id: mongoose.Types.ObjectId(),
    sort: 1610,
    name: "Community Leaders",
    description: "The Holy Grail",
    minClassRead: 400,
    minClassWrite: 400,
    minClassCreate: 400,
    lastPostTopic: null,
    lastPost: null,
    forumCategory: forumCategories[2]._id,
  },
];

const forumTopics = [
  {
    title: "Finances Update / Introducing the Whatminimal Shirt",
    author: user123,
    lastPost: null,
    lastPostAuthor: user123,
    isLocked: true,
    numPosts: 1,
    forum: forums[0]._id,
  },
  {
    title: "We'll Add Bounty to Your Requests!",
    author: staff,
    lastPost: null,
    lastPostAuthor: staff,
    numPosts: 22,
    forum: forums[0]._id,
  },
  {
    title: "The Stellar CD Design Thread",
    author: user456,
    lastPost: null,
    numPosts: 99,
    forum: forums[0]._id,
  },
  {
    title: "Approved Ripping Tools: Morituri",
    author: user789,
    lastPost: null,
    numPosts: 1232,
    forum: forums[0]._id,
  },
  {
    title: "Automatically update your existing library to better quality",
    author: user123,
    lastPost: null,
    numPosts: 21,
    forum: forums[0]._id,
  },
  {
    title: "Add a country of origin field to music communities",
    author: user456,
    lastPost: null,
    numPosts: 13,
    forum: forums[0]._id,
  },
  {
    title: "Notifications I didn't sign up for",
    author: user789,
    lastPost: null,
    numPosts: 3,
    forum: forums[0]._id,
  },
  {
    title: "Lets Talk Football!",
    author: user123,
    lastPost: null,
    numPosts: 233,
    forum: forums[0]._id,
  },
  {
    title: "TMI",
    author: user456,
    lastPost: null,
    numPosts: 213,
    forum: forums[0]._id,
  },
  {
    title: "Where is meaning if it depends on both subject and object?",
    author: user789,
    lastPost: null,
    numPosts: 5133,
    forum: forums[0]._id,
  },
  {
    title: "[Region] The London Thread",
    author: user123,
    lastPost: null,
    numPosts: 22,
    forum: forums[0]._id,
  },
  {
    title: "Your favorite comic publisher???",
    author: user456,
    lastPost: null,
    numPosts: 22,
    forum: forums[0]._id,
  },
  {
    title: "Portable Media Players",
    author: user789,
    lastPost: null,
    numPosts: 2214,
    forum: forums[0]._id,
  },
  {
    title: "New Daft Punk Album This Spring",
    author: user123,
    lastPost: null,
    numPosts: 414,
    forum: forums[0]._id,
  },
  {
    title: "The Stellar CD, 2023, April: Music Submission Round!",
    author: user456,
    lastPost: null,
    numPosts: 23,
    forum: forums[0]._id,
  },
];

module.exports = { forumTopics, forumCategories, forums };
