const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const UserRankSchema = new Schema({
  field1: {
    type: Number,
    required: true
  },
  field2: {
    type: String,
    required: true
  },
  field3: {
    site_leech: Boolean,
    site_upload: Boolean,
    site_vote: Boolean,
    site_submit_requests: Boolean,
    site_advanced_search: Boolean,
    site_top10: Boolean,
    site_advanced_top10: Boolean,
    site_album_votes: Boolean,
    site_communities_notify: Boolean,
    site_collages_create: Boolean,
    site_collages_manage: Boolean,
    site_collages_subscribe: Boolean,
    site_collages_personal: Boolean,
    site_collages_renamepersonal: Boolean,
    site_make_bookmarks: Boolean,
    site_edit_wiki: Boolean,
    site_can_invite_always: Boolean,
    site_send_unlimited_invites: Boolean,
    site_moderate_requests: Boolean,
    site_delete_artist: Boolean,
    site_moderate_forums: Boolean,
    site_admin_forums: Boolean,
    site_forums_double_post: Boolean,
    site_view_flow: Boolean,
    site_view_full_log: Boolean,
    site_view_community_snatchlist: Boolean,
    site_recommend_own: Boolean,
    site_manage_recommendations: Boolean,
    site_delete_tag: Boolean,
    site_disable_ip_history: Boolean,
    zip_downloader: Boolean,
    site_debug: Boolean,
    site_proxy_images: Boolean,
    site_search_many: Boolean,
    users_edit_usernames: Boolean,
    users_edit_ratio: Boolean,
    users_edit_own_ratio: Boolean,
    users_edit_titles: Boolean,
    users_edit_avatars: Boolean,
    users_edit_invites: Boolean,
    users_edit_watch_hours: Boolean,
    users_edit_reset_keys: Boolean,
    users_edit_profiles: Boolean,
    users_view_friends: Boolean,
    users_reset_own_keys: Boolean,
    users_edit_password: Boolean,
    users_promote_below: Boolean,
    users_promote_to: Boolean,
    users_give_donor: Boolean,
    users_warn: Boolean,
    users_disable_users: Boolean,
    users_disable_posts: Boolean,
    users_disable_any: Boolean,
    users_delete_users: Boolean,
    users_view_invites: Boolean,
    users_view_seedleech: Boolean,
    users_view_uploaded: Boolean,
    users_view_keys: Boolean,
    users_view_ips: Boolean,
    users_view_email: Boolean,
    users_invite_notes: Boolean,
    users_override_paranoia: Boolean,
    users_logout: Boolean,
    users_make_invisible: Boolean,
    users_mod: Boolean,
    communities_edit: Boolean,
    communities_delete: Boolean,
    communities_delete_fast: Boolean,
    communities_freeleech: Boolean,
    communities_search_fast: Boolean,
    communities_hide_dnu: Boolean,
    communities_fix_ghosts: Boolean,
    admin_manage_news: Boolean,
    admin_manage_blog: Boolean,
    admin_manage_polls: Boolean,
    admin_manage_forums: Boolean,
    admin_manage_fls: Boolean,
    admin_reports: Boolean,
    admin_advanced_user_search: Boolean,
    admin_create_users: Boolean,
    admin_donor_log: Boolean,
    admin_manage_ipbans: Boolean,
    admin_dnu: Boolean,
    admin_clear_cache: Boolean,
    admin_whitelist: Boolean,
    admin_manage_permissions: Boolean,
  },
  field4: {
    type: String,
    default: ''
  },
  field5: {
    type: String,
    default: ''
  },
  field6: {
    type: Number,
    default: 0
  }
});

module.exports = UserRank = mongoose.model('UserRank', UserRankSchema);
